### ISSUE TITLE
Apache license does not include year or author name

### ISSUE THREAD

**Issue by euclio** [nishanths/license#18]
```sh
$ license -name Alice -y 2017 apache-2.0
```

The output includes `Copyright {yyyy} {name of copyright owner}` instead of filling in the supplied values.

**Comment by nishanths** [comment]
The placeholders are intentional: that section of the license explains to readers how to use the license for their own projects. For instance, see the same line in `httpd`'s license: https://github.com/apache/httpd/blob/trunk/LICENSE#L189, which has the `Copyright {yyyy} {name of copyright owner}` part.

**Comment by euclio** [comment]
Ah, my mistake! Thanks.
