### ISSUE TITLE
"--name" and "--year" option not working with Apache-2.0 License

### ISSUE THREAD

**Issue by ganler** [nishanths/license#36]
## How I installed license

```shell
yay -S nishanths-license-git
```

## Symptom

![image](https://user-images.githubusercontent.com/38074777/139557657-2cad3ae1-0381-43a9-aef1-357f880d7a63.png)

![image](https://user-images.githubusercontent.com/38074777/139557664-1ee11d9f-55fe-4543-8ca2-90414eeb97ad.png)

**Comment by nishanths** [comment]
Thanks for the report. I believe this is similar to https://github.com/nishanths/license/issues/32 (please let me know if you find out otherwise). The line:

```
Copyright [yyyy] [name of copyright owner]
```

is under the following section of the license:

> APPENDIX: How to apply the Apache License to your work.

For this reason, the [yyyy] and [name ...] placeholders should be left as is. Solr, which is an Apache project, also leaves this line as is in its license; see the link below.

https://github.com/apache/lucene-solr/blob/4d6c3e17c6574b5d0fa626359a7f14c435bc5e9f/LICENSE#L189
