### ISSUE TITLE
Missing ISC license

### ISSUE THREAD

**Issue by yuri-norwood** [nishanths/license#37]
The README mentions the [ISC](https://www.isc.org/licenses/) license, although as far as I can see it was never supported.

![image](https://user-images.githubusercontent.com/76186754/141214794-576b6f0c-fbc5-4933-a6fe-3713b37f2c4a.png)

I can open a PR to add it, or was there a reason it was removed?

**Comment by nishanths** [comment]
I don't think there was a conscious decision to remove the license (if it existed before), so +1 for including it. Thanks.

Regarding whether the license existed before: 

Originally the `license` command used to obtain licenses at runtime via the https://api.github.com/licenses API. It may have been that the GitHub API back then returned the `isc` license, but later stopped doing it. A few years later, the `license` command was changed to include the available licenses at build time. When this change was made, the licenses were obtained from the current list on the GitHub API, so `isc` may have been missed at this time.

Or it may be that the license has been missing from the start.

**Comment by nishanths** [comment]
> It may have been that the GitHub API back then returned the isc license, but later stopped doing it.

This may have been it.

In commit https://github.com/nishanths/license/commit/49ed1a1b64e2387b15b104c341286c7b07571e02 in which the licenses were switched to being included in the binary instead of fetched at runtime, we see a lgpl-3.0 template added in the commit. The license list used at the time of the commit was obtained from the `/licenses` API at https://api.github.com/licenses (possibly with header `Accept: application/vnd.github.v3+json`). I think this means lgpl-3.0 was being returned by the API around the time of the commit. But right now the API doesn't include lgpl-3.0. 

Something similar may have happened with `isc` as well, except that its removal happened even before commit 49ed1a1.

**Comment by yuri-norwood** [comment]
Ah that makes sense, no worries then, glad I caught it then.

**Comment by yuri-norwood** [comment]
Huh, fun fact, the Github API still has ICS lying around, it's just not listed. Makes you wonder what other licenses are supported by the API but not listed 🤔 

https://api.github.com/licenses/isc
