### ISSUE TITLE
adjust `Go / fmt (pull_request)` check

### ISSUE THREAD

**Issue by nishanths** [nishanths/license#43]
Firstly, the check auto-formats and auto-commits changes to branches. This is behavior I tend to not like. We should modify the check to only check that the code is formatted. It should not auto-commit any changes.

Secondly, it seems to fail when run on a PR for branches on other remotes. For example, see this [run][1].

[1]: https://github.com/nishanths/license/actions/runs/3230131715/jobs/5290280909

**Comment by norwd** [comment]
@nishanths, instead of using [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action), maybe the workflow could use [reviewdog/action-suggester](https://github.com/marketplace/actions/reviewdog-suggester-suggest-any-code-changes-based-on-diff-with-reviewdog) to suggest the `go fmt` changes instead of just committing them directly?

**Comment by nishanths** [comment]
@norwd: Replied in the [pull request](https://github.com/nishanths/license/pull/45#issuecomment-1276799683).

**Comment by nishanths** [comment]
Fixed in #46.
