### ISSUE TITLE
Getting "Error: Empty installation" for Homebrew install

### ISSUE THREAD

**Issue by g12mcgov** [nishanths/license#7]
Hi there, 

I was trying to install this package via Homebrew, and followed all the steps, however, on the last step where it actually installs the package, I got the following error:

    ==> Installing license from nishanths/tap
    ==> Downloading https://storage.googleapis.com/license-binaries/darwin_amd64/0.1.2/license.tar.gz
    ######################################################################## 100.0%
    Error: Empty installation

Any ideas?

**Comment by nishanths** [comment]
Hi @g12mcgov, thanks for reporting. Unfortunately I was unable to repro on either of my `darwin_amd64` machines. Could you try installing with the verbose flag and see if that brings up any interesting info? `brew install --verbose nishanths/tap/license`

**Comment by acjackman** [comment]
Just tried installing via Homebrew (10.11.2 (15C50)) and I'm getting that same error, any suggestions?
 
    $ brew update
    $ brew install --verbose nishanths/tap/license
    ==> Installing license from nishanths/tap
    ==> Downloading https://storage.googleapis.com/license-binaries/darwin_amd64/0.1.2/license.tar.gz
    Already downloaded: /Library/Caches/Homebrew/license-0.1.2.tar.gz
    ==> Verifying license-0.1.2.tar.gz checksum
    tar xvf /Library/Caches/Homebrew/license-0.1.2.tar.gz
    x license
    Error: Empty installation

**Comment by nishanths** [comment]
@acjackman @g12mcgov I'm seeing the error now too. Investigating.

**Comment by nishanths** [comment]
With commit https://github.com/Homebrew/homebrew/commit/915ac06db21acc5c9595b2223cc39b9672f34c4a, homebrew raises an "Empty installation" exception if it appeared that no significant files were included during install. One of the [filenames](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/metafiles.rb) that homebrew filtered out as non-significant metafiles are files named `license`.

As it turns out, the only file that being installed in our case is a single binary file named `license`. Hence the "Empty installation" exception.

**Comment by nishanths** [comment]
## Fix

```bash
$ rm /Library/Caches/Homebrew/license-0.1.2.tar.gz  # remove cached file
$ brew update
$ brew tap nishanths/tap
$ brew install nishanths/tap/license
```

Verify it works:

```
$ license version
v0.1.2
```

Let me know if you run into issues :+1:

**Comment by acjackman** [comment]
Fixed issue for me. Thanks!
