### ISSUE TITLE
flags and GNU GPL

### ISSUE THREAD

**Issue by colundrum** [nishanths/license#8]
Hi,

When I use

    license --name COLUNDRUM --year 2016 gpl-3.0

The output is the original license without customization about project title, name and year.

Same issue with

- agpl-3.0
- apache-2.0
- gpl-2.0
- lgpl-2.1
- lgpl-3.0

Thanks

**Comment by nishanths** [comment]
Hi @colundrum 

Are you referring to the placeholders for the year and name of author in the following section (and similar sections) in the licenses you listed?

```
How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    {one line to give the program's name and a brief idea of what it does.}
    Copyright (C) {year}  {name of author}

   ...

    {project}  Copyright (C) {year}  {fullname}
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.

The hypothetical commands `show w' and `show c' should show the appropriate
parts of the General Public License.  Of course, your program's commands
might be different; for a GUI interface, you would use an "about box".

  ...
```

If I'm not mistaken, the placeholders in this section should remain as they are, because these sections explain how to use GPL/LGPL for the reader's own programs. GitHub also does not replace the placeholders when you [create a new repo](https://github.com/new) from the web interface with these licenses.

That said, it would be nice to get a professional opinion on this.
